// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sistema_Gestion_Funeraria__LP2_.Models;

#nullable disable

namespace Sistema_Gestion_Funeraria__LP2_.Migrations
{
    [DbContext(typeof(FunerariaContext))]
    [Migration("20240622224020_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Sistema_Gestion_Funeraria__LP2_.Models.Atributo", b =>
                {
                    b.Property<int>("IdAtributo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Atributo");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAtributo"));

                    b.Property<decimal>("Costo")
                        .HasColumnType("money");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("Estatus")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdAtributo")
                        .HasName("PK__Atributo__5ECA4A186BBE52E3");

                    b.ToTable("Atributo", (string)null);
                });

            modelBuilder.Entity("Sistema_Gestion_Funeraria__LP2_.Models.AtributoCategoria", b =>
                {
                    b.Property<int>("IdAtributo")
                        .HasColumnType("int")
                        .HasColumnName("ID_Atributo");

                    b.Property<int>("IdCategoria")
                        .HasColumnType("int")
                        .HasColumnName("ID_Categoria");

                    b.Property<decimal>("Costo")
                        .HasColumnType("money");

                    b.HasKey("IdAtributo", "IdCategoria")
                        .HasName("PK__Atributo__1EE0EA6043280821");

                    b.HasIndex("IdCategoria");

                    b.ToTable("Atributo_Categorias", (string)null);
                });

            modelBuilder.Entity("Sistema_Gestion_Funeraria__LP2_.Models.Cargo", b =>
                {
                    b.Property<int>("IdCargo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Cargo");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCargo"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdCargo")
                        .HasName("PK__Cargo__8D69B95FB68199D1");

                    b.ToTable("Cargo", (string)null);
                });

            modelBuilder.Entity("Sistema_Gestion_Funeraria__LP2_.Models.Categoria", b =>
                {
                    b.Property<int>("IdCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Categoria");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCategoria"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("TotalCobertura")
                        .HasColumnType("money")
                        .HasColumnName("Total_Cobertura");

                    b.HasKey("IdCategoria")
                        .HasName("PK__Categori__02AA0785B34B9C91");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("Sistema_Gestion_Funeraria__LP2_.Models.Defuncione", b =>
                {
                    b.Property<int>("IdDefuncion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Defuncion");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDefuncion"));

                    b.Property<byte[]>("CertificacionDefuncion")
                        .IsRequired()
                        .HasColumnType("image")
                        .HasColumnName("Certificacion_Defuncion");

                    b.Property<DateOnly>("FechaFallecimiento")
                        .HasColumnType("date")
                        .HasColumnName("Fecha_Fallecimiento");

                    b.Property<DateOnly>("FechaNacimiento")
                        .HasColumnType("date")
                        .HasColumnName("Fecha_Nacimiento");

                    b.Property<TimeOnly>("HorarioEntrada")
                        .HasColumnType("time")
                        .HasColumnName("Horario_Entrada");

                    b.Property<TimeOnly>("HorarioSalida")
                        .HasColumnType("time")
                        .HasColumnName("Horario_Salida");

                    b.Property<int?>("IdIdentificacion")
                        .HasColumnType("int")
                        .HasColumnName("ID_Identificacion");

                    b.Property<int?>("IdSala")
                        .HasColumnType("int")
                        .HasColumnName("ID_Sala");

                    b.Property<string>("Identificacion")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("NombreDifunto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Nombre_Difunto");

                    b.Property<string>("Representante")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RepresentanteDireccion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Representante_Direccion");

                    b.Property<string>("RepresentanteTelefono")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)")
                        .HasColumnName("Representante_Telefono");

                    b.HasKey("IdDefuncion")
                        .HasName("PK__Defuncio__E05EBEA85A1B991F");

                    b.HasIndex("IdIdentificacion");

                    b.HasIndex("IdSala");

                    b.ToTable("Defunciones");
                });

            modelBuilder.Entity("Sistema_Gestion_Funeraria__LP2_.Models.Empleado", b =>
                {
                    b.Property<int>("IdEmpleado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Empleado");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEmpleado"));

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("IdCargo")
                        .HasColumnType("int")
                        .HasColumnName("ID_Cargo");

                    b.Property<int?>("IdIdentificacion")
                        .HasColumnType("int")
                        .HasColumnName("ID_Identificacion");

                    b.Property<int?>("IdJornadaLaboral")
                        .HasColumnType("int")
                        .HasColumnName("ID_Jornada_Laboral");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NumDocumento")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("IdEmpleado")
                        .HasName("PK__Empleado__B7872C90AFF4E8ED");

                    b.HasIndex("IdCargo");

                    b.HasIndex("IdIdentificacion");

                    b.ToTable("Empleados");
                });

            modelBuilder.Entity("Sistema_Gestion_Funeraria__LP2_.Models.FacturacionesAtributo", b =>
                {
                    b.Property<int>("IdAtributo")
                        .HasColumnType("int")
                        .HasColumnName("ID_Atributo");

                    b.Property<int>("IdDefuncion")
                        .HasColumnType("int")
                        .HasColumnName("ID_Defuncion");

                    b.Property<decimal>("Costo")
                        .HasColumnType("money");

                    b.HasKey("IdAtributo", "IdDefuncion")
                        .HasName("PK__Facturac__C0CFA1F2AB574138");

                    b.HasIndex("IdDefuncion");

                    b.ToTable("Facturaciones_Atributo", (string)null);
                });

            modelBuilder.Entity("Sistema_Gestion_Funeraria__LP2_.Models.FacturacionesServicio", b =>
                {
                    b.Property<int>("IdServicio")
                        .HasColumnType("int")
                        .HasColumnName("ID_Servicio");

                    b.Property<int>("IdDefuncion")
                        .HasColumnType("int")
                        .HasColumnName("ID_Defuncion");

                    b.Property<decimal>("Costo")
                        .HasColumnType("money");

                    b.HasKey("IdServicio", "IdDefuncion")
                        .HasName("PK__Facturac__87371E6E5CF4A5BB");

                    b.HasIndex("IdDefuncion");

                    b.ToTable("Facturaciones_Servicios", (string)null);
                });

            modelBuilder.Entity("Sistema_Gestion_Funeraria__LP2_.Models.JornadaLaboral", b =>
                {
                    b.Property<int>("IdJornadaLaboral")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Jornada_Laboral");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdJornadaLaboral"));

                    b.Property<DateOnly>("FechaEntrada")
                        .HasColumnType("date")
                        .HasColumnName("Fecha_Entrada");

                    b.Property<DateOnly>("FechaSalida")
                        .HasColumnType("date")
                        .HasColumnName("Fecha_Salida");

                    b.Property<int?>("IdLocalidad")
                        .HasColumnType("int")
                        .HasColumnName("ID_Localidad");

                    b.HasKey("IdJornadaLaboral")
                        .HasName("PK__Jornada___4D9539810E0370F1");

                    b.HasIndex("IdLocalidad");

                    b.ToTable("Jornada_Laboral", (string)null);
                });

            modelBuilder.Entity("Sistema_Gestion_Funeraria__LP2_.Models.LibroFirma", b =>
                {
                    b.Property<int>("IdLibroFirma")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Libro_Firma");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLibroFirma"));

                    b.Property<int?>("IdDefuncion")
                        .HasColumnType("int")
                        .HasColumnName("ID_Defuncion");

                    b.Property<string>("Mensaje")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("NombreFirma")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Nombre_Firma");

                    b.HasKey("IdLibroFirma")
                        .HasName("PK__Libro_Fi__4A04D334864E53AC");

                    b.HasIndex("IdDefuncion");

                    b.ToTable("Libro_Firma", (string)null);
                });

            modelBuilder.Entity("Sistema_Gestion_Funeraria__LP2_.Models.Localidad", b =>
                {
                    b.Property<int>("IdLocalidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Localidad");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLocalidad"));

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("IdContacto1")
                        .HasColumnType("int")
                        .HasColumnName("ID_Contacto1");

                    b.Property<int?>("IdContacto2")
                        .HasColumnType("int")
                        .HasColumnName("ID_Contacto2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.HasKey("IdLocalidad")
                        .HasName("PK__Localida__8ACE3DA1F196609E");

                    b.ToTable("Localidad", (string)null);
                });

            modelBuilder.Entity("Sistema_Gestion_Funeraria__LP2_.Models.Sala", b =>
                {
                    b.Property<int>("IdSala")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Sala");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSala"));

                    b.Property<int>("Capacidad")
                        .HasColumnType("int");

                    b.Property<string>("Estatus")
                        .IsRequired()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .IsFixedLength();

                    b.Property<int?>("IdCategoria")
                        .HasColumnType("int")
                        .HasColumnName("ID_Categoria");

                    b.Property<int?>("IdLocalidad")
                        .HasColumnType("int")
                        .HasColumnName("ID_Localidad");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdSala")
                        .HasName("PK__Salas__2071DEA7B374F345");

                    b.HasIndex("IdCategoria");

                    b.HasIndex("IdLocalidad");

                    b.ToTable("Salas");
                });

            modelBuilder.Entity("Sistema_Gestion_Funeraria__LP2_.Models.Servicio", b =>
                {
                    b.Property<int>("IdServicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Servicio");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdServicio"));

                    b.Property<decimal>("Costo")
                        .HasColumnType("money");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdServicio")
                        .HasName("PK__Servicio__1932F584415698B8");

                    b.ToTable("Servicios");
                });

            modelBuilder.Entity("Sistema_Gestion_Funeraria__LP2_.Models.ServiciosCategoria", b =>
                {
                    b.Property<int>("IdServicio")
                        .HasColumnType("int")
                        .HasColumnName("ID_Servicio");

                    b.Property<int>("IdCategoria")
                        .HasColumnType("int")
                        .HasColumnName("ID_Categoria");

                    b.Property<decimal>("Costo")
                        .HasColumnType("money");

                    b.HasKey("IdServicio", "IdCategoria")
                        .HasName("PK__Servicio__591855FC0A40FA83");

                    b.HasIndex("IdCategoria");

                    b.ToTable("Servicios_Categorias", (string)null);
                });

            modelBuilder.Entity("Sistema_Gestion_Funeraria__LP2_.Models.TipoIdentificacion", b =>
                {
                    b.Property<int>("IdIdentificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Identificacion");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdIdentificacion"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdIdentificacion")
                        .HasName("PK__Tipo_Ide__2D8D9EE1D17D799B");

                    b.ToTable("Tipo_Identificacion", (string)null);
                });

            modelBuilder.Entity("Sistema_Gestion_Funeraria__LP2_.Models.AtributoCategoria", b =>
                {
                    b.HasOne("Sistema_Gestion_Funeraria__LP2_.Models.Atributo", "IdAtributoNavigation")
                        .WithMany("AtributoCategoria")
                        .HasForeignKey("IdAtributo")
                        .IsRequired()
                        .HasConstraintName("FK__Atributo___ID_At__2E1BDC42");

                    b.HasOne("Sistema_Gestion_Funeraria__LP2_.Models.Categoria", "IdCategoriaNavigation")
                        .WithMany("AtributoCategoria")
                        .HasForeignKey("IdCategoria")
                        .IsRequired()
                        .HasConstraintName("FK__Atributo___ID_Ca__2F10007B");

                    b.Navigation("IdAtributoNavigation");

                    b.Navigation("IdCategoriaNavigation");
                });

            modelBuilder.Entity("Sistema_Gestion_Funeraria__LP2_.Models.Defuncione", b =>
                {
                    b.HasOne("Sistema_Gestion_Funeraria__LP2_.Models.TipoIdentificacion", "IdIdentificacionNavigation")
                        .WithMany("Defunciones")
                        .HasForeignKey("IdIdentificacion")
                        .HasConstraintName("FK__Defuncion__ID_Id__3A81B327");

                    b.HasOne("Sistema_Gestion_Funeraria__LP2_.Models.Sala", "IdSalaNavigation")
                        .WithMany("Defunciones")
                        .HasForeignKey("IdSala")
                        .HasConstraintName("FK__Defuncion__ID_Sa__398D8EEE");

                    b.Navigation("IdIdentificacionNavigation");

                    b.Navigation("IdSalaNavigation");
                });

            modelBuilder.Entity("Sistema_Gestion_Funeraria__LP2_.Models.Empleado", b =>
                {
                    b.HasOne("Sistema_Gestion_Funeraria__LP2_.Models.Cargo", "IdCargoNavigation")
                        .WithMany("Empleados")
                        .HasForeignKey("IdCargo")
                        .HasConstraintName("FK__Empleados__ID_Ca__403A8C7D");

                    b.HasOne("Sistema_Gestion_Funeraria__LP2_.Models.TipoIdentificacion", "IdIdentificacionNavigation")
                        .WithMany("Empleados")
                        .HasForeignKey("IdIdentificacion")
                        .HasConstraintName("FK__Empleados__ID_Id__3F466844");

                    b.Navigation("IdCargoNavigation");

                    b.Navigation("IdIdentificacionNavigation");
                });

            modelBuilder.Entity("Sistema_Gestion_Funeraria__LP2_.Models.FacturacionesAtributo", b =>
                {
                    b.HasOne("Sistema_Gestion_Funeraria__LP2_.Models.Atributo", "IdAtributoNavigation")
                        .WithMany("FacturacionesAtributos")
                        .HasForeignKey("IdAtributo")
                        .IsRequired()
                        .HasConstraintName("FK__Facturaci__ID_At__49C3F6B7");

                    b.HasOne("Sistema_Gestion_Funeraria__LP2_.Models.Defuncione", "IdDefuncionNavigation")
                        .WithMany("FacturacionesAtributos")
                        .HasForeignKey("IdDefuncion")
                        .IsRequired()
                        .HasConstraintName("FK__Facturaci__ID_De__4AB81AF0");

                    b.Navigation("IdAtributoNavigation");

                    b.Navigation("IdDefuncionNavigation");
                });

            modelBuilder.Entity("Sistema_Gestion_Funeraria__LP2_.Models.FacturacionesServicio", b =>
                {
                    b.HasOne("Sistema_Gestion_Funeraria__LP2_.Models.Defuncione", "IdDefuncionNavigation")
                        .WithMany("FacturacionesServicios")
                        .HasForeignKey("IdDefuncion")
                        .IsRequired()
                        .HasConstraintName("FK__Facturaci__ID_De__4E88ABD4");

                    b.HasOne("Sistema_Gestion_Funeraria__LP2_.Models.Servicio", "IdServicioNavigation")
                        .WithMany("FacturacionesServicios")
                        .HasForeignKey("IdServicio")
                        .IsRequired()
                        .HasConstraintName("FK__Facturaci__ID_Se__4D94879B");

                    b.Navigation("IdDefuncionNavigation");

                    b.Navigation("IdServicioNavigation");
                });

            modelBuilder.Entity("Sistema_Gestion_Funeraria__LP2_.Models.JornadaLaboral", b =>
                {
                    b.HasOne("Sistema_Gestion_Funeraria__LP2_.Models.Localidad", "IdLocalidadNavigation")
                        .WithMany("JornadaLaborals")
                        .HasForeignKey("IdLocalidad")
                        .HasConstraintName("FK__Jornada_L__ID_Lo__440B1D61");

                    b.Navigation("IdLocalidadNavigation");
                });

            modelBuilder.Entity("Sistema_Gestion_Funeraria__LP2_.Models.LibroFirma", b =>
                {
                    b.HasOne("Sistema_Gestion_Funeraria__LP2_.Models.Defuncione", "IdDefuncionNavigation")
                        .WithMany("LibroFirmas")
                        .HasForeignKey("IdDefuncion")
                        .HasConstraintName("FK__Libro_Fir__ID_De__46E78A0C");

                    b.Navigation("IdDefuncionNavigation");
                });

            modelBuilder.Entity("Sistema_Gestion_Funeraria__LP2_.Models.Sala", b =>
                {
                    b.HasOne("Sistema_Gestion_Funeraria__LP2_.Models.Categoria", "IdCategoriaNavigation")
                        .WithMany("Salas")
                        .HasForeignKey("IdCategoria")
                        .HasConstraintName("FK__Salas__ID_Catego__29572725");

                    b.HasOne("Sistema_Gestion_Funeraria__LP2_.Models.Localidad", "IdLocalidadNavigation")
                        .WithMany("Salas")
                        .HasForeignKey("IdLocalidad")
                        .HasConstraintName("FK__Salas__ID_Locali__286302EC");

                    b.Navigation("IdCategoriaNavigation");

                    b.Navigation("IdLocalidadNavigation");
                });

            modelBuilder.Entity("Sistema_Gestion_Funeraria__LP2_.Models.ServiciosCategoria", b =>
                {
                    b.HasOne("Sistema_Gestion_Funeraria__LP2_.Models.Categoria", "IdCategoriaNavigation")
                        .WithMany("ServiciosCategoria")
                        .HasForeignKey("IdCategoria")
                        .IsRequired()
                        .HasConstraintName("FK__Servicios__ID_Ca__34C8D9D1");

                    b.HasOne("Sistema_Gestion_Funeraria__LP2_.Models.Servicio", "IdServicioNavigation")
                        .WithMany("ServiciosCategoria")
                        .HasForeignKey("IdServicio")
                        .IsRequired()
                        .HasConstraintName("FK__Servicios__ID_Se__33D4B598");

                    b.Navigation("IdCategoriaNavigation");

                    b.Navigation("IdServicioNavigation");
                });

            modelBuilder.Entity("Sistema_Gestion_Funeraria__LP2_.Models.Atributo", b =>
                {
                    b.Navigation("AtributoCategoria");

                    b.Navigation("FacturacionesAtributos");
                });

            modelBuilder.Entity("Sistema_Gestion_Funeraria__LP2_.Models.Cargo", b =>
                {
                    b.Navigation("Empleados");
                });

            modelBuilder.Entity("Sistema_Gestion_Funeraria__LP2_.Models.Categoria", b =>
                {
                    b.Navigation("AtributoCategoria");

                    b.Navigation("Salas");

                    b.Navigation("ServiciosCategoria");
                });

            modelBuilder.Entity("Sistema_Gestion_Funeraria__LP2_.Models.Defuncione", b =>
                {
                    b.Navigation("FacturacionesAtributos");

                    b.Navigation("FacturacionesServicios");

                    b.Navigation("LibroFirmas");
                });

            modelBuilder.Entity("Sistema_Gestion_Funeraria__LP2_.Models.Localidad", b =>
                {
                    b.Navigation("JornadaLaborals");

                    b.Navigation("Salas");
                });

            modelBuilder.Entity("Sistema_Gestion_Funeraria__LP2_.Models.Sala", b =>
                {
                    b.Navigation("Defunciones");
                });

            modelBuilder.Entity("Sistema_Gestion_Funeraria__LP2_.Models.Servicio", b =>
                {
                    b.Navigation("FacturacionesServicios");

                    b.Navigation("ServiciosCategoria");
                });

            modelBuilder.Entity("Sistema_Gestion_Funeraria__LP2_.Models.TipoIdentificacion", b =>
                {
                    b.Navigation("Defunciones");

                    b.Navigation("Empleados");
                });
#pragma warning restore 612, 618
        }
    }
}
